eveonline-assistant/characters/urls.py
"""
URLs for the characters app
"""
from django.conf.urls import patterns, url

from .views import AddCharacter, ManageCharacters, ManageApiKeys, CharacterDetail, UpdateCharacter, AddApiKey, \
    DeleteApiKey


urlpatterns = patterns(
    '',
    # URL pattern for the UserListView
    url(
        regex=r'^add/$',
        view=AddCharacter.as_view(),
        name='add'
    ),
    url(
        regex=r'^manage/$',
        view=ManageCharacters.as_view(),
        name='manage'
    ),
    url(
        regex=r'^manage/(?P<slug>\S+)/fetch/$',
        view=UpdateCharacter.as_view(slug_url_kwarg='slug'),
        name='fetch'
    ),
    url(
        regex=r'^manage/(?P<slug>\S+)/$',
        view=CharacterDetail.as_view(slug_url_kwarg='slug'),
        name='detail'
    ),
    url(
        regex=r'^apis/add$',
        view=AddApiKey.as_view(),
        name='add_api'
    ),
    url(
        regex=r'^apis/manage/$',
        view=ManageApiKeys.as_view(),
        name='manage_apis'
    ),
    url(
        regex=r'^apis/delete/(?P<pk>\d+)/$',
        view=DeleteApiKey.as_view(),
        name='delete_api'
    ),
)

eveonline-assistant/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name="home"),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name="about"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls go here
    url(r'^skills/', include('skills.urls', namespace='skills')),
    url(r'^characters/', include('characters.urls', namespace='characters')),
    url(r'^plans/', include('plans.urls', namespace='plans'))
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eveonline-assistant/plans/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    # URL pattern for the UserListView
    url(
        regex=r'^add/$',
        view=views.AddPlan.as_view(),
        name='add'
    ),
    url(
        regex=r'^manage/$',
        view=views.ManagePlans.as_view(),
        name='manage'
    ),
    url(
        regex=r'^manage/(?P<plan_id>\d+)/$',
        view=views.PlanDetail.as_view(pk_url_kwarg='plan_id'),
        name='detail'
    ),
    url(
        regex=r'^addToPlan/$',
        view=views.AddSkillToPlan.as_view(),
        name='add_to_plan'
    ),
)

eveonline-assistant/characters/forms.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Field, HTML
from django import forms
from django.forms import ModelForm
from evelink.api import APIError

from .models import ApiKey, Character


class ApiKeyForm(ModelForm):
    """
    Simple form to add a new API Key
    """

    def __init__(self, user, *args, **kwargs):
        super(ApiKeyForm, self).__init__(*args, **kwargs)
        self.user = user
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.layout = Layout(
            Fieldset(
                'Add new API Key',
                'key_id',
                'verification_code'
            ),
            FormActions(
                Submit('save', 'Add', css_class='btn btn-success'),
            )
        )

    def clean(self):
        """
        Check the API Key is actually valid with CCP

        :return: cleaned data as usual
        :rtype: dict
        :raise forms.ValidationError: Passing through the APIError from CCP
        """
        cleaned_data = super(ApiKeyForm, self).clean()
        apikey = ApiKey(
            key_id=cleaned_data.get('key_id'),
            verification_code=cleaned_data.get('verification_code'),
            user=self.user
        )
        try:
            apikey.get_characters()
        except APIError as e:
            raise forms.ValidationError(
                '%s' % e.message,
                'api-error'
            )
        return cleaned_data

    def save(self, commit=True):
        instance = super(ApiKeyForm, self).save(commit)
        characters = instance.get_characters()
        for cid in characters.keys():
            char, _ = Character.objects.get_or_create(
                id=cid,
                defaults={
                    'user': self.user,
                    'name': characters[cid]['name'],
                    'skillpoints': 0,
                    'enabled': False
                }
            )
            char.apikey = instance
            char.save()
            char.update_attributes()
        return instance

    class Meta:
        """
        Form settings
        """
        model = ApiKey
        exclude = ['user', ]


class CharacterForm(forms.Form):
    """
    Form to add character with a field to select API Key or add new
    """

    def __init__(self, user=None, *args, **kwargs):
        super(CharacterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'

        self.fields['char_ids'] = forms.ModelMultipleChoiceField(
            queryset=user.characters.filter(enabled=False),
            label='Characters'
        )
        self.fields['char_ids'].help_text = ''

        self.helper.layout = Layout(
            Fieldset(
                'Add new character(s)',
                Field('char_ids', placeholder='Select characters')
            ),
            FormActions(
                Submit(
                    'add-char',
                    'Add characters',
                    css_class='btn btn-success',
                ),
                HTML(
                    '<a href="{% url "characters:add_api" %}" class="btn '
                    'btn-info">Add API Key</a>'
                ),
            )
        )

    class Meta:
        """
        Form settings
        """
        model = ApiKey
        exclude = ['user', ]

eveonline-assistant/characters/views.py
from collections import OrderedDict

from braces.views import LoginRequiredMixin
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView, CreateView, \
    FormView, DeleteView

from .forms import ApiKeyForm, CharacterForm
from .utils import UserIsOwnerMixin
from .models import ApiKey, Character


class AddCharacter(LoginRequiredMixin, FormView):
    form_class = CharacterForm
    template_name = 'characters/character_form.html'

    def get_form_kwargs(self):
        kwargs = super(AddCharacter, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        for character in form.cleaned_data['char_ids']:
            character.enabled = True
            character.save()
        self.success_url = form.cleaned_data['char_ids'][0].get_absolute_url()
        return super(AddCharacter, self).form_valid(form)


class ManageCharacters(LoginRequiredMixin, ListView):
    model = Character

    def get_queryset(self):
        queryset = self.model.objects.filter(
            user=self.request.user,
            enabled=True
        )
        return queryset


class UpdateCharacter(UserIsOwnerMixin, DetailView):
    model = Character

    def get(self, request, *args, **kwargs):
        character = self.get_object()
        if not character.enabled:
            raise Http404
        message = character.update_character_sheet()
        messages.add_message(request, message['status'], message['text'])
        return redirect(self.request.META.get('HTTP_REFERER'))


class AddApiKey(LoginRequiredMixin, CreateView):
    model = ApiKey
    form_class = ApiKeyForm
    success_url = reverse_lazy('characters:add')

    def get_form_kwargs(self):
        kwargs = super(AddApiKey, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AddApiKey, self).form_valid(form)


class ManageApiKeys(LoginRequiredMixin, ListView):
    model = ApiKey

    def get_queryset(self):
        queryset = self.model.objects.filter(user=self.request.user)
        return queryset


class DeleteApiKey(UserIsOwnerMixin, DeleteView):
    model = ApiKey
    success_url = reverse_lazy('characters:manage_apis')


class CharacterDetail(UserIsOwnerMixin, DetailView):
    model = Character

    def get_context_data(self, **kwargs):
        character = self.get_object()
        if not character.enabled:
            raise Http404
        skills_list = character.skilltrained_set.select_related().order_by(
            'skill__group',
            'skill__name')
        groups = OrderedDict()
        for skill in skills_list:
            if skill.skill.group.name not in groups:
                groups[skill.skill.group.name] = []
            groups[skill.skill.group.name].append(skill)
        context = {
            'groups': character.skill_groups
        }
        return super(CharacterDetail, self).get_context_data(**context)

eveonline-assistant/templates/characters/apikey_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete API Key{% endblock %}

{% block content %}
  <h2>Delete API Key</h2>
  <p>Really delete API Key {{ object.key_id }} and all associated content?</p>
  <form method="post" action=".">
    {% csrf_token %}
    <button class="btn btn-danger"
            type="submit">Delete</button>
  </form>
{% endblock %}

eveonline-assistant/templates/characters/apikey_form.html
{% extends "base_form.html" %}

{% block title %}Add New API Key{% endblock %}

{% block header %}API Key{% endblock %}

eveonline-assistant/templates/characters/apikey_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}

{% block title %}API Keys{% endblock %}

{% block content %}

  <div class="container">

    <div class="row">
      <div class="col-xs-12">
        <h1>API Keys</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <div class="bs-component">
          <table class="table table-striped table-hover">
            <thead>
            <tr>
              <th>Key ID</th>
              <th>Verification Code</th>
              <th>Actions</th>
            </tr>
            </thead>
            {% for api in apikey_list %}
              <tr>
                <td>{{ api.key_id }}</td>
                <td>{{ api.verification_code }}</td>
                <td>
                  <a href="{% url 'characters:delete_api' api.pk %}">Delete</a>
                </td>
              </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>

  </div>

{% endblock content %}

eveonline-assistant/templates/characters/character_add.html
{% extends "base.html" %}
{% block title %}Add Character{% endblock %}
{% block content %}
  <h1>Add character</h1>
  <div class="well bs-component">
    <form class="form-horizontal" id="add-character-form" method="post">
      {% csrf_token %}
      <fieldset>
        <div class="form-group">
          <label for="input-key-id" class="col-lg-2 control-label">Key ID</label>

          <div class="col-lg-10">
            <input type="text"
                   class="form-control"
                   id="input-key-id"
                   placeholder="Key ID"
                   name="keyid"/>
          </div>
        </div>
        <div class="form-group">
          <label for="input-vcode"
                 class="col-lg-2 control-label">Verification Code</label>

          <div class="col-lg-10">
            <input type="text"
                   class="form-control"
                   id="input-vcode"
                   placeholder="Verification Code"
                   name="vcode"/>
          </div>
        </div>
        <div class="form-group">
          <label for="select-characters"
                 class="col-lg-2 control-label">Character(s)</label>

          <div class="col-lg-10">
            <input type="text"
                   id="select-characters"
                   class="form-control input-lg"
                   name="characters"/>
          </div>
        </div>
      </fieldset>
      <button class="btn btn-info"
              id="btn-get-characters"
              data-loading-text="Getting characters..."
              type="button">
        Get Characters
      </button>
      <button class="btn btn-success"
              style="display: none;"
              id="btn-add-characters"
              data-loading-text="Adding characters..."
              type="submit">Add characters
      </button>
    </form>
  </div>
  {% if request.user.had_apikeys %}

  {% endif %}
{% endblock %}

eveonline-assistant/templates/characters/character_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Character: {{ character.name }}{% endblock %}

{% block content %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="panel-title">{{ character.name }}</h1>
      </div>
      <div class="panel-body">
        <div class="col-sm-4">
          <img src="//image.eveonline.com/Character/{{ character.id }}_256.jpg"/>
        </div>
        <div class="col-sm-8">
        <div class="row">
          <dl class="dl-horizontal">
            {% for attribute in character.attributes.select_related.all %}
              <dt>{{ attribute.attribute.name|capfirst }}</dt>
              <dd>{{ attribute.base }} + {{ attribute.bonus }}</dd>
            {% endfor %}
          </dl>
        </div>
        <div class="row">
          <a href="{{ character.get_fetch_url }}" class="btn
          btn-success">Update</a>
        </div>
        </div>
      </div>
    </div>
    {% include "characters/skills_accordion.html" %}
{% endblock content %}

eveonline-assistant/templates/characters/character_form.html
{% extends "base_form.html" %}

{% block title %}Add New Character{% endblock %}

{% block header %}Characters{% endblock %}

{% block form %}
{% if not user.has_disabled_characters %}
  <div class="alert alert-block alert-danger">
    <h4 class="alert-heading">All characters enabled
    </h4>
    <ul>
      <a href="{% url "characters:add_api" %}">Add a new API Key</a>
      to add more characters
    </ul>
  </div>
{% else %}
  {{ block.super }}
{% endif %}
{% endblock %}

eveonline-assistant/templates/characters/character_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}

{% block title %}Characters{% endblock %}

{% block content %}

  <div class="container">

    <div class="row">
      <div class="col-xs-12">
        <h1>Characters</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <div class="bs-component">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Actions</th>
              </tr>
            </thead>
            {% for character in character_list %}
              <tr>
                <td>
                  <a href="{{ character.get_absolute_url }}">
                    {{ character.name }}
                  </a>
                </td>
                <td>
                  <a href="{{ character.get_fetch_url}}">
                    Update</a> |
                  <a href="#">Delete</a>
                </td>
              </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>

  </div>

{% endblock content %}

eveonline-assistant/templates/characters/skills_accordion.html
{% load humanize %}
<div class="panel-group" id="skills-accordion">
  {% for group in groups %}
    {% with in_progress=group.progress %}
    <div class="panel {% if in_progress %}panel-info{% else %}panel-default{% endif %}">
      <a data-toggle="collapse"
         data-parent="#skills-accordion"
         href="#collapse{{ forloop.counter }}"
         class="{% if group.progress %}panel-info{% else %}panel-default{% endif %}">
        <div class="panel-heading">
          <h4 class="panel-title">
            {{ group.skill__group__name }} <b class="caret"></b>
            <span class="pull-right">
              SP: {{ group.sp_sum|intcomma }}
              ({{ group.trained }} / {{ group.total }})
            </span>
          </h4>
        </div>
      </a>

      <div id="collapse{{ forloop.counter }}"
           class="panel-collapse collapse">
        <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Skill</th>
                <th class="hidden-xs hidden-sm">Progress to next level</th>
                <th>Time to next level</th>
                <th class="hidden-xs hidden-sm">Skill points</th>
                <th>Level</th>
              </tr>
            </thead>
            <tbody>
            {% for skill_known in group.skills %}
              {% with skill=skill_known.skill %}
                <tr class="
                  {% if skill_known.progress > 0.0 and skill_known.progress < 100.0 %}
                    warning
                  {% elif skill_known.progress == 100.0 and skill_known.level == 5 %}
                    success
                  {% endif %}">
                  <td>{{ skill.name }} ({{ skill.rank }}x)</td>
                  <td class="hidden-xs hidden-sm">
                    <div class="progress">
                      <div class="progress-bar" style="width: {{ skill_known.progress }}%;"></div>
                    </div>
                  </td>
                  <td class="text-right">
                    {{ skill_known.time_to_next_level_as_str|default:"" }}
                  </td>
                  <td class="text-center hidden-xs hidden-sm">
                    {{ skill_known.skillpoints|intcomma }}
                    {% if skill_known.sp_to_next_level > 0 %}/
                    {{ skill_known.sp_to_next_level|intcomma }}{% endif %}
                  </td>
                  <td class="text-center">
                    <span class="badge">{{ skill_known.level }}</span>
                  </td>
                </tr>
              {% endwith %}
            {% endfor %}
            <tr class="info">
              <td>{{ in_progress.skill.name }} ({{ in_progress.skill.rank }}x)</td>
              <td class="hidden-xs hidden-sm">
                <div class="progress">
                  <div class="progress-bar" style="width:
                  {{ in_progress.progress }}%;"></div>
                </div>
              </td>
              <td class="text-right">
                {{ in_progress.skill.time_to_next_level_as_str|default:"" }}
              </td>
              <td class="text-center hidden-xs hidden-sm">
                {{ in_progress.current_sp|intcomma }}
                /
                {{ in_progress.end_sp|intcomma }}
              </td>
              <td class="text-center">
                <span class="badge">{{ in_progress.level }}</span>
              </td>
            </tr>
            </tbody>
          </table>
      </div>
    </div>
    {% endwith %}
  {% endfor %}
</div>