eveonline-assistant/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name="home"),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name="about"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls go here
    url(r'^skills/', include('skills.urls', namespace='skills')),
    url(r'^characters/', include('characters.urls', namespace='characters')),
    url(r'^plans/', include('plans.urls', namespace='plans'))
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eveonline-assistant/plans/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    # URL pattern for the UserListView
    url(
        regex=r'^add/$',
        view=views.AddPlan.as_view(),
        name='add'
    ),
    url(
        regex=r'^manage/$',
        view=views.ManagePlans.as_view(),
        name='manage'
    ),
    url(
        regex=r'^manage/(?P<plan_id>\d+)/$',
        view=views.PlanDetail.as_view(pk_url_kwarg='plan_id'),
        name='detail'
    ),
    url(
        regex=r'^addToPlan/$',
        view=views.AddSkillToPlan.as_view(),
        name='add_to_plan'
    ),
)

eveonline-assistant/skills/urls.py
from django.conf.urls import patterns, url

from .views import SkillsInGroups


urlpatterns = patterns(
    '',
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=SkillsInGroups.as_view(),
        name='list'
    ),
)

eveonline-assistant/skills/models.py
from django.db import models


class Group(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    name = models.CharField('Name', max_length=255)

    def __unicode__(self):
        return self.name

    @property
    def has_published_skills(self):
        return len(self.skills.filter(published=True)) > 0

    class Meta:
        ordering = ['name']


class Skill(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    published = models.BooleanField('Published', default=True)
    group = models.ForeignKey(
        'Group',
        verbose_name='Group',
        on_delete=models.CASCADE,
        related_name='skills'
    )
    name = models.CharField('Name', max_length=255)
    rank = models.IntegerField('Rank')
    description = models.TextField('Description')
    required_skills = models.ManyToManyField(
        'Requirement',
        verbose_name='Required skills',
        related_name='provided_skills',
        blank=True
    )
    primary_attribute = models.ForeignKey(
        'Attribute',
        verbose_name='Primary Attribute',
        on_delete=models.CASCADE,
        related_name='primary_for'
    )
    secondary_attribute = models.ForeignKey(
        'Attribute',
        verbose_name='Secondary Attribute',
        on_delete=models.CASCADE,
        related_name='secondary_for'
    )

    @property
    def skillpoints(self):
        return {
            0: 0,
            1: 250 * self.rank,
            2: 1415 * self.rank,
            3: 8000 * self.rank,
            4: 45255 * self.rank,
            5: 256000 * self.rank,
        }

    def sp_to_level(self, from_level=0, to_level=1):
        """
        Calculate the skillpoint requirement from one level to another
        :param from_level: int start level
        :param to_level: int end level
        :return: skillpoint total
        :rtype: int
        """
        total = self.skillpoints[to_level] - self.skillpoints[from_level]
        return total

    def time_to_level(self, from_level=0, to_level=1, pri_attr_value=1,
                      sec_attr_value=1):
        """
        Calculate the time taken to get from one level to another
        :param from_level: int start level
        :param to_level: int end level
        :param pri_attr_value: the primary attribute value for the calculation
        :param sec_attr_value: the secondary attribute value for the calculation
        :return: The number of seconds this training will take
        :rtype: int
        """
        sp = self.sp_to_level(from_level, to_level)
        points_per_second = (pri_attr_value + (sec_attr_value / 2)) / 60
        return int(sp / points_per_second)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Requirement(models.Model):
    skill = models.ForeignKey(
        'Skill',
        verbose_name='Skill',
        on_delete=models.CASCADE
    )
    level = models.IntegerField('Level')

    def __unicode__(self):
        return u'%s L%s' % (self.skill, self.level)


class Attribute(models.Model):
    name = models.CharField('Name', max_length=255)
    slot = models.IntegerField('Slot')

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['slot']

eveonline-assistant/skills/views.py
"""
Views for the Skills app
"""
from django.views.generic import ListView

from .models import Group


class SkillsInGroups(ListView):
    """
    Browse all skills view
    """
    model = Group

eveonline-assistant/templates/skills/group_list.html
{% extends "base.html" %}
{% load static i18n cache %}

{% block title %}Skills{% endblock %}

{% block content %}

  <div class="container">
    {% cache 86400 skill_list %}
      {% include "skills/skills_accordion.html" %}
    {% endcache %}
  </div>

{% endblock content %}

eveonline-assistant/templates/skills/skills_accordion.html
<div class="panel-group" id="skills-accordion">
  {% for group in group_list %}
    {% if group.has_published_skills %}
      <div class="panel panel-default">
        <a data-toggle="collapse"
           data-parent="#skills-accordion"
           href="#collapse{{ forloop.counter }}">
          <div class="panel-heading">
            <h4 class="panel-title">
              {{ group.name }} <b class="caret"></b>
            </h4>
          </div>
        </a>

        <div id="collapse{{ forloop.counter }}"
             class="panel-collapse collapse">
          <div class="panel-body">
            <table class="table table-striped table-hover" id="skills-list">
              <tbody>
              {% for skill in group.skills.all %}
                {% if skill.published %}
                  <tr>
                    <td>
                      <button class="btn btn-link btn-xs skill-btn"
                              value="{{ skill.id }}"
                              data-toggle="modal"
                              data-target="#skill-modal">
                        {{ skill.name }}
                      </button>
                    </td>
                  </tr>
                {% endif %}
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    {% endif %}
  {% endfor %}
</div>